/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "eventapi",
            "endpoint": "https://vmnns3oggg.execute-api.us-east-2.amazonaws.com/eventenv",
            "region": "us-east-2"
        },
        {
            "name": "noreqapi",
            "endpoint": "https://syhc43z8d5.execute-api.us-east-2.amazonaws.com/eventenv",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:b46dc8cd-8061-4a8e-842b-f1b7d0521162",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_KUdOCRRET",
    "aws_user_pools_web_client_id": "76mqea22mbc27qupfd4ukhkh33",
    "oauth": {}
};


export default awsmobile;
